# ---
# - name: Exercise #1
#   hosts: localhost

#   roles:
#    - print
#    - setup

---
# Exercise for setting up a web server in an EC
- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: 174.129.89.192
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
   - setup